services:
  # Data base 2: Olist
  postgres-olist-source:
      image: postgres:16
      container_name: postgres-olist-source
      environment:
        - POSTGRES_USER=${SOURCE_POSTGRES_USER}
        - POSTGRES_PASSWORD=${SOURCE_POSTGRES_PASSWORD}
        - POSTGRES_DB=${SOURCE_POSTGRES_DB}
      ports:
        - "5433:5432" # Host: 5433 -> Container: 5432
      volumes:
        - olist_source_data:/var/lib/postgresql/data
        - ./init-scripts-olist:/docker-entrypoint-initdb.d
        - ./data:/data-csv

  # Data base 3: Data Warehouse
  postgres-dwh:
    image: postgres:16
    container_name: postgres-dwh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432" # Host: 5434 -> Kontener: 5432
    volumes:
      - dwh_data:/var/lib/postgresql/data
      - ./init-scripts-dwh:/docker-entrypoint-initdb.d

volumes:
  olist_source_data:
  dwh_data: